# Generated by Django 4.2.4 on 2023-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todonote',
            options={'ordering': ['-id'], 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.AddField(
            model_name='todonote',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='время создания'),
        ),
    ]
